/**
 * Think 1 第二版 Level 1 词汇数据
 * 来源：Think 1 Second Edition 学生用书 + Wordwall + Quizlet + StudyStack
 * 生成时间: 2026-06-26
 *
 * 数据结构:
 * { lesson, word, pos, meaning, topic, subcategory }
 * lesson: 0=Welcome, 1-12=Unit 1-12
 */
const vocabulary = {
  "meta": {
    "description": "Think 1 Second Edition Level 1 (CEFR A2) 分单元词汇数据",
    "total": 475
  },
  "vocabulary": [

    // ============ Welcome - 教室物品 ============
    {"lesson":0,"word":"desk","pos":"n","meaning":"书桌","topic":"🏫 教室与学习","subcategory":"教室物品"},
    {"lesson":0,"word":"chair","pos":"n","meaning":"椅子","topic":"🏫 教室与学习","subcategory":"教室物品"},
    {"lesson":0,"word":"board","pos":"n","meaning":"黑板","topic":"🏫 教室与学习","subcategory":"教室物品"},
    {"lesson":0,"word":"ruler","pos":"n","meaning":"尺子","topic":"🏫 教室与学习","subcategory":"教室物品"},
    {"lesson":0,"word":"pencil","pos":"n","meaning":"铅笔","topic":"🏫 教室与学习","subcategory":"教室物品"},
    {"lesson":0,"word":"pen","pos":"n","meaning":"钢笔","topic":"🏫 教室与学习","subcategory":"教室物品"},
    {"lesson":0,"word":"notebook","pos":"n","meaning":"笔记本","topic":"🏫 教室与学习","subcategory":"教室物品"},
    {"lesson":0,"word":"backpack","pos":"n","meaning":"背包","topic":"🏫 教室与学习","subcategory":"教室物品"},
    {"lesson":0,"word":"scissors","pos":"n","meaning":"剪刀","topic":"🏫 教室与学习","subcategory":"教室物品"},
    {"lesson":0,"word":"dictionary","pos":"n","meaning":"词典","topic":"🏫 教室与学习","subcategory":"教室物品"},
    {"lesson":0,"word":"calculator","pos":"n","meaning":"计算器","topic":"🏫 教室与学习","subcategory":"教室物品"},
    {"lesson":0,"word":"book","pos":"n","meaning":"书","topic":"🏫 教室与学习","subcategory":"教室物品"},
    {"lesson":0,"word":"computer","pos":"n","meaning":"电脑","topic":"🏫 教室与学习","subcategory":"教室物品"},
    {"lesson":0,"word":"homework","pos":"n","meaning":"家庭作业","topic":"🏫 教室与学习","subcategory":"学习用语"},
    {"lesson":0,"word":"classroom","pos":"n","meaning":"教室","topic":"🏫 教室与学习","subcategory":"学习用语"},
    {"lesson":0,"word":"teacher","pos":"n","meaning":"老师","topic":"🏫 教室与学习","subcategory":"学习用语"},
    {"lesson":0,"word":"student","pos":"n","meaning":"学生","topic":"🏫 教室与学习","subcategory":"学习用语"},
    {"lesson":0,"word":"classmate","pos":"n","meaning":"同学","topic":"🏫 教室与学习","subcategory":"学习用语"},
    {"lesson":0,"word":"lesson","pos":"n","meaning":"课程","topic":"🏫 教室与学习","subcategory":"学习用语"},

    // ============ Welcome - 方位介词 ============
    {"lesson":0,"word":"on","pos":"prep","meaning":"在……上面","topic":"📍 方位介词","subcategory":"基础方位"},
    {"lesson":0,"word":"in","pos":"prep","meaning":"在……里面","topic":"📍 方位介词","subcategory":"基础方位"},
    {"lesson":0,"word":"under","pos":"prep","meaning":"在……下面","topic":"📍 方位介词","subcategory":"基础方位"},
    {"lesson":0,"word":"behind","pos":"prep","meaning":"在……后面","topic":"📍 方位介词","subcategory":"基础方位"},
    {"lesson":0,"word":"next to","pos":"prep","meaning":"在……旁边","topic":"📍 方位介词","subcategory":"基础方位"},
    {"lesson":0,"word":"between","pos":"prep","meaning":"在……之间","topic":"📍 方位介词","subcategory":"基础方位"},
    {"lesson":0,"word":"in front of","pos":"prep","meaning":"在……前面","topic":"📍 方位介词","subcategory":"基础方位"},
    {"lesson":0,"word":"near","pos":"prep","meaning":"在……附近","topic":"📍 方位介词","subcategory":"基础方位"},
    {"lesson":0,"word":"opposite","pos":"prep","meaning":"在……对面","topic":"📍 方位介词","subcategory":"进阶方位"},
    {"lesson":0,"word":"above","pos":"prep","meaning":"在……上方","topic":"📍 方位介词","subcategory":"进阶方位"},

    // ============ Welcome - 国家与国籍 ============
    {"lesson":0,"word":"the United States","pos":"","meaning":"美国","topic":"🌎 国家与国籍","subcategory":"国家"},
    {"lesson":0,"word":"Brazil","pos":"n","meaning":"巴西","topic":"🌎 国家与国籍","subcategory":"国家"},
    {"lesson":0,"word":"China","pos":"n","meaning":"中国","topic":"🌎 国家与国籍","subcategory":"国家"},
    {"lesson":0,"word":"the UK","pos":"","meaning":"英国","topic":"🌎 国家与国籍","subcategory":"国家"},
    {"lesson":0,"word":"Britain","pos":"n","meaning":"英国","topic":"🌎 国家与国籍","subcategory":"国家"},
    {"lesson":0,"word":"Mexico","pos":"n","meaning":"墨西哥","topic":"🌎 国家与国籍","subcategory":"国家"},
    {"lesson":0,"word":"Japan","pos":"n","meaning":"日本","topic":"🌎 国家与国籍","subcategory":"国家"},
    {"lesson":0,"word":"Spain","pos":"n","meaning":"西班牙","topic":"🌎 国家与国籍","subcategory":"国家"},
    {"lesson":0,"word":"Australia","pos":"n","meaning":"澳大利亚","topic":"🌎 国家与国籍","subcategory":"国家"},
    {"lesson":0,"word":"American","pos":"adj","meaning":"美国的；美国人","topic":"🌎 国家与国籍","subcategory":"国籍"},
    {"lesson":0,"word":"Brazilian","pos":"adj","meaning":"巴西的；巴西人","topic":"🌎 国家与国籍","subcategory":"国籍"},
    {"lesson":0,"word":"Chinese","pos":"adj","meaning":"中国的；中国人","topic":"🌎 国家与国籍","subcategory":"国籍"},
    {"lesson":0,"word":"British","pos":"adj","meaning":"英国的；英国人","topic":"🌎 国家与国籍","subcategory":"国籍"},
    {"lesson":0,"word":"Mexican","pos":"adj","meaning":"墨西哥的；墨西哥人","topic":"🌎 国家与国籍","subcategory":"国籍"},
    {"lesson":0,"word":"Japanese","pos":"adj","meaning":"日本的；日本人","topic":"🌎 国家与国籍","subcategory":"国籍"},
    {"lesson":0,"word":"English","pos":"n","meaning":"英语","topic":"🌎 国家与国籍","subcategory":"语言"},
    {"lesson":0,"word":"Portuguese","pos":"n","meaning":"葡萄牙语","topic":"🌎 国家与国籍","subcategory":"语言"},
    {"lesson":0,"word":"Spanish","pos":"n","meaning":"西班牙语","topic":"🌎 国家与国籍","subcategory":"语言"},

    // ============ Unit 1 - Having a Good Time ============
    {"lesson":1,"word":"hobby","pos":"n","meaning":"爱好","topic":"🎮 爱好与活动","subcategory":"兴趣爱好"},
    {"lesson":1,"word":"play an instrument","pos":"","meaning":"演奏乐器","topic":"🎮 爱好与活动","subcategory":"兴趣爱好"},
    {"lesson":1,"word":"play the piano","pos":"","meaning":"弹钢琴","topic":"🎮 爱好与活动","subcategory":"兴趣爱好"},
    {"lesson":1,"word":"play the guitar","pos":"","meaning":"弹吉他","topic":"🎮 爱好与活动","subcategory":"兴趣爱好"},
    {"lesson":1,"word":"write a blog","pos":"","meaning":"写博客","topic":"🎮 爱好与活动","subcategory":"兴趣爱好"},
    {"lesson":1,"word":"take photos","pos":"","meaning":"拍照","topic":"🎮 爱好与活动","subcategory":"兴趣爱好"},
    {"lesson":1,"word":"keep a pet","pos":"","meaning":"养宠物","topic":"🎮 爱好与活动","subcategory":"兴趣爱好"},
    {"lesson":1,"word":"collect things","pos":"","meaning":"收集物品","topic":"🎮 爱好与活动","subcategory":"兴趣爱好"},
    {"lesson":1,"word":"be in a club","pos":"","meaning":"参加俱乐部","topic":"🎮 爱好与活动","subcategory":"兴趣爱好"},
    {"lesson":1,"word":"join a club","pos":"","meaning":"加入俱乐部","topic":"🎮 爱好与活动","subcategory":"兴趣爱好"},
    {"lesson":1,"word":"do exercise","pos":"","meaning":"锻炼","topic":"🎮 爱好与活动","subcategory":"兴趣爱好"},
    {"lesson":1,"word":"go shopping","pos":"","meaning":"去购物","topic":"🎮 爱好与活动","subcategory":"兴趣爱好"},
    {"lesson":1,"word":"chat online","pos":"","meaning":"网上聊天","topic":"🎮 爱好与活动","subcategory":"兴趣爱好"},
    {"lesson":1,"word":"read books","pos":"","meaning":"读书","topic":"🎮 爱好与活动","subcategory":"兴趣爱好"},
    {"lesson":1,"word":"watch films","pos":"","meaning":"看电影","topic":"🎮 爱好与活动","subcategory":"兴趣爱好"},
    {"lesson":1,"word":"listen to music","pos":"","meaning":"听音乐","topic":"🎮 爱好与活动","subcategory":"兴趣爱好"},
    {"lesson":1,"word":"play computer games","pos":"","meaning":"玩电脑游戏","topic":"🎮 爱好与活动","subcategory":"兴趣爱好"},
    {"lesson":1,"word":"hang out with friends","pos":"","meaning":"和朋友出去玩","topic":"🎮 爱好与活动","subcategory":"兴趣爱好"},
    {"lesson":1,"word":"make friends","pos":"","meaning":"交朋友","topic":"🎮 爱好与活动","subcategory":"兴趣爱好"},
    {"lesson":1,"word":"do homework","pos":"","meaning":"做作业","topic":"🎮 爱好与活动","subcategory":"兴趣爱好"},
    {"lesson":1,"word":"free time","pos":"","meaning":"空闲时间","topic":"🎮 爱好与活动","subcategory":"时间表达"},
    {"lesson":1,"word":"have fun","pos":"","meaning":"玩得开心","topic":"🎮 爱好与活动","subcategory":"have 搭配"},
    {"lesson":1,"word":"have a good time","pos":"","meaning":"玩得愉快","topic":"🎮 爱好与活动","subcategory":"have 搭配"},
    {"lesson":1,"word":"have a rest","pos":"","meaning":"休息一下","topic":"🎮 爱好与活动","subcategory":"have 搭配"},
    {"lesson":1,"word":"have dinner","pos":"","meaning":"吃晚饭","topic":"🎮 爱好与活动","subcategory":"have 搭配"},
    {"lesson":1,"word":"have time","pos":"","meaning":"有时间","topic":"🎮 爱好与活动","subcategory":"have 搭配"},
    {"lesson":1,"word":"have hobbies","pos":"","meaning":"有爱好","topic":"🎮 爱好与活动","subcategory":"have 搭配"},
    {"lesson":1,"word":"have a shower","pos":"","meaning":"洗澡","topic":"🎮 爱好与活动","subcategory":"have 搭配"},
    {"lesson":1,"word":"have a problem","pos":"","meaning":"有问题","topic":"🎮 爱好与活动","subcategory":"have 搭配"},
    {"lesson":1,"word":"enjoy","pos":"v","meaning":"享受；喜欢","topic":"🏃 动作行为","subcategory":"常用动词"},
    {"lesson":1,"word":"enjoy life","pos":"","meaning":"享受生活","topic":"🎮 爱好与活动","subcategory":"常用短语"},
    {"lesson":1,"word":"get bored","pos":"","meaning":"感到无聊","topic":"🎮 爱好与活动","subcategory":"常用短语"},
    {"lesson":1,"word":"find more time for","pos":"","meaning":"腾出更多时间","topic":"🎮 爱好与活动","subcategory":"常用短语"},
    {"lesson":1,"word":"practise a lot","pos":"","meaning":"大量练习","topic":"🎮 爱好与活动","subcategory":"常用短语"},
    {"lesson":1,"word":"different places","pos":"","meaning":"不同的地方","topic":"🎮 爱好与活动","subcategory":"常用表达"},
    {"lesson":1,"word":"long queue","pos":"","meaning":"长队","topic":"🎮 爱好与活动","subcategory":"常用表达"},
    {"lesson":1,"word":"use an app","pos":"","meaning":"使用应用程序","topic":"💻 科技与设备","subcategory":"常用短语"},
    {"lesson":1,"word":"use a map","pos":"","meaning":"使用地图","topic":"💻 科技与设备","subcategory":"常用短语"},
    {"lesson":1,"word":"message on my phone","pos":"","meaning":"用手机发信息","topic":"💻 科技与设备","subcategory":"常用短语"},
    {"lesson":1,"word":"turn off the lights","pos":"","meaning":"关灯","topic":"🏃 动作行为","subcategory":"常用短语"},
    {"lesson":1,"word":"be late","pos":"","meaning":"迟到","topic":"🏃 动作行为","subcategory":"常用短语"},
    {"lesson":1,"word":"be careful","pos":"","meaning":"小心","topic":"🏃 动作行为","subcategory":"常用短语"},
    {"lesson":1,"word":"be ready for","pos":"","meaning":"为……做好准备","topic":"🏃 动作行为","subcategory":"常用短语"},

    // ============ 频率副词 (跨单元基础词汇) ============
    {"lesson":1,"word":"always","pos":"adv","meaning":"总是","topic":"📅 时间与顺序","subcategory":"频率副词"},
    {"lesson":1,"word":"usually","pos":"adv","meaning":"通常","topic":"📅 时间与顺序","subcategory":"频率副词"},
    {"lesson":1,"word":"often","pos":"adv","meaning":"经常","topic":"📅 时间与顺序","subcategory":"频率副词"},
    {"lesson":1,"word":"sometimes","pos":"adv","meaning":"有时","topic":"📅 时间与顺序","subcategory":"频率副词"},
    {"lesson":1,"word":"never","pos":"adv","meaning":"从不","topic":"📅 时间与顺序","subcategory":"频率副词"},
    {"lesson":1,"word":"every day","pos":"","meaning":"每天","topic":"📅 时间与顺序","subcategory":"频率副词"},
    {"lesson":1,"word":"twice a week","pos":"","meaning":"一周两次","topic":"📅 时间与顺序","subcategory":"频率副词"},

    // ============ Unit 2 - Money and How to Spend It ============
    {"lesson":2,"word":"money","pos":"n","meaning":"钱","topic":"🛍️ 购物与消费","subcategory":"购物用语"},
    {"lesson":2,"word":"price","pos":"n","meaning":"价格","topic":"🛍️ 购物与消费","subcategory":"购物用语"},
    {"lesson":2,"word":"size","pos":"n","meaning":"尺码","topic":"🛍️ 购物与消费","subcategory":"购物用语"},
    {"lesson":2,"word":"medium","pos":"adj","meaning":"中号的","topic":"🛍️ 购物与消费","subcategory":"购物用语"},
    {"lesson":2,"word":"cheap","pos":"adj","meaning":"便宜的","topic":"🛍️ 购物与消费","subcategory":"购物用语"},
    {"lesson":2,"word":"expensive","pos":"adj","meaning":"昂贵的","topic":"🛍️ 购物与消费","subcategory":"购物用语"},
    {"lesson":2,"word":"pay","pos":"v","meaning":"付款","topic":"🛍️ 购物与消费","subcategory":"购物用语"},
    {"lesson":2,"word":"buy","pos":"v","meaning":"买","topic":"🛍️ 购物与消费","subcategory":"购物用语"},
    {"lesson":2,"word":"sell","pos":"v","meaning":"卖","topic":"🛍️ 购物与消费","subcategory":"购物用语"},
    {"lesson":2,"word":"try on","pos":"","meaning":"试穿","topic":"🛍️ 购物与消费","subcategory":"购物用语"},
    {"lesson":2,"word":"spend","pos":"v","meaning":"花费","topic":"🛍️ 购物与消费","subcategory":"购物用语"},
    {"lesson":2,"word":"save","pos":"v","meaning":"节省；储蓄","topic":"🛍️ 购物与消费","subcategory":"购物用语"},
    {"lesson":2,"word":"supermarket","pos":"n","meaning":"超市","topic":"🛍️ 购物与消费","subcategory":"商店类型"},
    {"lesson":2,"word":"bookshop","pos":"n","meaning":"书店","topic":"🛍️ 购物与消费","subcategory":"商店类型"},
    {"lesson":2,"word":"chemist's","pos":"n","meaning":"药店","topic":"🛍️ 购物与消费","subcategory":"商店类型"},
    {"lesson":2,"word":"clothes shop","pos":"","meaning":"服装店","topic":"🛍️ 购物与消费","subcategory":"商店类型"},
    {"lesson":2,"word":"coffee shop","pos":"","meaning":"咖啡店","topic":"🛍️ 购物与消费","subcategory":"商店类型"},
    {"lesson":2,"word":"shoe shop","pos":"","meaning":"鞋店","topic":"🛍️ 购物与消费","subcategory":"商店类型"},
    {"lesson":2,"word":"department store","pos":"","meaning":"百货商店","topic":"🛍️ 购物与消费","subcategory":"商店类型"},
    {"lesson":2,"word":"newsagent's","pos":"n","meaning":"报刊亭","topic":"🛍️ 购物与消费","subcategory":"商店类型"},
    {"lesson":2,"word":"mobile phone shop","pos":"","meaning":"手机店","topic":"🛍️ 购物与消费","subcategory":"商店类型"},
    {"lesson":2,"word":"sports shop","pos":"","meaning":"体育用品店","topic":"🛍️ 购物与消费","subcategory":"商店类型"},
    {"lesson":2,"word":"belt","pos":"n","meaning":"皮带","topic":"🛍️ 购物与消费","subcategory":"服装"},
    {"lesson":2,"word":"dress","pos":"n","meaning":"连衣裙","topic":"🛍️ 购物与消费","subcategory":"服装"},
    {"lesson":2,"word":"jumper","pos":"n","meaning":"套头衫","topic":"🛍️ 购物与消费","subcategory":"服装"},
    {"lesson":2,"word":"shoes","pos":"n","meaning":"鞋子","topic":"🛍️ 购物与消费","subcategory":"服装"},
    {"lesson":2,"word":"trainers","pos":"n","meaning":"运动鞋","topic":"🛍️ 购物与消费","subcategory":"服装"},
    {"lesson":2,"word":"boots","pos":"n","meaning":"靴子","topic":"🛍️ 购物与消费","subcategory":"服装"},
    {"lesson":2,"word":"jacket","pos":"n","meaning":"夹克","topic":"🛍️ 购物与消费","subcategory":"服装"},
    {"lesson":2,"word":"shirt","pos":"n","meaning":"衬衫","topic":"🛍️ 购物与消费","subcategory":"服装"},
    {"lesson":2,"word":"shorts","pos":"n","meaning":"短裤","topic":"🛍️ 购物与消费","subcategory":"服装"},
    {"lesson":2,"word":"trousers","pos":"n","meaning":"裤子","topic":"🛍️ 购物与消费","subcategory":"服装"},
    {"lesson":2,"word":"hat","pos":"n","meaning":"帽子","topic":"🛍️ 购物与消费","subcategory":"服装"},
    {"lesson":2,"word":"T-shirt","pos":"n","meaning":"T恤","topic":"🛍️ 购物与消费","subcategory":"服装"},
    {"lesson":2,"word":"socks","pos":"n","meaning":"袜子","topic":"🛍️ 购物与消费","subcategory":"服装"},
    {"lesson":2,"word":"jeans","pos":"n","meaning":"牛仔裤","topic":"🛍️ 购物与消费","subcategory":"服装"},

    // ============ Unit 3 - Food for Life ============
    {"lesson":3,"word":"apple","pos":"n","meaning":"苹果","topic":"🍕 食物与饮食","subcategory":"食材"},
    {"lesson":3,"word":"banana","pos":"n","meaning":"香蕉","topic":"🍕 食物与饮食","subcategory":"食材"},
    {"lesson":3,"word":"pear","pos":"n","meaning":"梨","topic":"🍕 食物与饮食","subcategory":"食材"},
    {"lesson":3,"word":"strawberry","pos":"n","meaning":"草莓","topic":"🍕 食物与饮食","subcategory":"食材"},
    {"lesson":3,"word":"watermelon","pos":"n","meaning":"西瓜","topic":"🍕 食物与饮食","subcategory":"食材"},
    {"lesson":3,"word":"carrots","pos":"n","meaning":"胡萝卜","topic":"🍕 食物与饮食","subcategory":"食材"},
    {"lesson":3,"word":"peppers","pos":"n","meaning":"甜椒","topic":"🍕 食物与饮食","subcategory":"食材"},
    {"lesson":3,"word":"onions","pos":"n","meaning":"洋葱","topic":"🍕 食物与饮食","subcategory":"食材"},
    {"lesson":3,"word":"mushrooms","pos":"n","meaning":"蘑菇","topic":"🍕 食物与饮食","subcategory":"食材"},
    {"lesson":3,"word":"spinach","pos":"n","meaning":"菠菜","topic":"🍕 食物与饮食","subcategory":"食材"},
    {"lesson":3,"word":"beans","pos":"n","meaning":"豆子","topic":"🍕 食物与饮食","subcategory":"食材"},
    {"lesson":3,"word":"chilli","pos":"n","meaning":"辣椒","topic":"🍕 食物与饮食","subcategory":"食材"},
    {"lesson":3,"word":"omelette","pos":"n","meaning":"煎蛋卷","topic":"🍕 食物与饮食","subcategory":"食材"},
    {"lesson":3,"word":"salad","pos":"n","meaning":"沙拉","topic":"🍕 食物与饮食","subcategory":"食材"},
    {"lesson":3,"word":"tacos","pos":"n","meaning":"墨西哥卷饼","topic":"🍕 食物与饮食","subcategory":"食材"},
    {"lesson":3,"word":"cake","pos":"n","meaning":"蛋糕","topic":"🍕 食物与饮食","subcategory":"食材"},
    {"lesson":3,"word":"bread","pos":"n","meaning":"面包","topic":"🍕 食物与饮食","subcategory":"食材"},
    {"lesson":3,"word":"rice","pos":"n","meaning":"米饭","topic":"🍕 食物与饮食","subcategory":"食材"},
    {"lesson":3,"word":"pasta","pos":"n","meaning":"意大利面","topic":"🍕 食物与饮食","subcategory":"食材"},
    {"lesson":3,"word":"pizza","pos":"n","meaning":"披萨","topic":"🍕 食物与饮食","subcategory":"食材"},
    {"lesson":3,"word":"sausage","pos":"n","meaning":"香肠","topic":"🍕 食物与饮食","subcategory":"食材"},
    {"lesson":3,"word":"ham","pos":"n","meaning":"火腿","topic":"🍕 食物与饮食","subcategory":"食材"},
    {"lesson":3,"word":"steak","pos":"n","meaning":"牛排","topic":"🍕 食物与饮食","subcategory":"食材"},
    {"lesson":3,"word":"chicken","pos":"n","meaning":"鸡肉","topic":"🍕 食物与饮食","subcategory":"食材"},
    {"lesson":3,"word":"fish","pos":"n","meaning":"鱼","topic":"🍕 食物与饮食","subcategory":"食材"},
    {"lesson":3,"word":"egg","pos":"n","meaning":"鸡蛋","topic":"🍕 食物与饮食","subcategory":"食材"},
    {"lesson":3,"word":"cheese","pos":"n","meaning":"奶酪","topic":"🍕 食物与饮食","subcategory":"食材"},
    {"lesson":3,"word":"yoghurt","pos":"n","meaning":"酸奶","topic":"🍕 食物与饮食","subcategory":"食材"},
    {"lesson":3,"word":"milk","pos":"n","meaning":"牛奶","topic":"🍕 食物与饮食","subcategory":"食材"},
    {"lesson":3,"word":"butter","pos":"n","meaning":"黄油","topic":"🍕 食物与饮食","subcategory":"食材"},
    {"lesson":3,"word":"coffee","pos":"n","meaning":"咖啡","topic":"🍕 食物与饮食","subcategory":"饮品"},
    {"lesson":3,"word":"tea","pos":"n","meaning":"茶","topic":"🍕 食物与饮食","subcategory":"饮品"},
    {"lesson":3,"word":"water","pos":"n","meaning":"水","topic":"🍕 食物与饮食","subcategory":"饮品"},
    {"lesson":3,"word":"juice","pos":"n","meaning":"果汁","topic":"🍕 食物与饮食","subcategory":"饮品"},
    {"lesson":3,"word":"cook","pos":"v","meaning":"烹饪","topic":"🍕 食物与饮食","subcategory":"烹饪方法"},
    {"lesson":3,"word":"roast","pos":"v","meaning":"烤（肉类/蔬菜）","topic":"🍕 食物与饮食","subcategory":"烹饪方法"},
    {"lesson":3,"word":"boil","pos":"v","meaning":"煮","topic":"🍕 食物与饮食","subcategory":"烹饪方法"},
    {"lesson":3,"word":"grill","pos":"v","meaning":"烤（用烤架）","topic":"🍕 食物与饮食","subcategory":"烹饪方法"},
    {"lesson":3,"word":"fry","pos":"v","meaning":"煎/炸","topic":"🍕 食物与饮食","subcategory":"烹饪方法"},
    {"lesson":3,"word":"delicious","pos":"adj","meaning":"美味的","topic":"🍕 食物与饮食","subcategory":"食物形容词"},
    {"lesson":3,"word":"tasty","pos":"adj","meaning":"可口的","topic":"🍕 食物与饮食","subcategory":"食物形容词"},
    {"lesson":3,"word":"yummy","pos":"adj","meaning":"好吃的","topic":"🍕 食物与饮食","subcategory":"食物形容词"},
    {"lesson":3,"word":"sweet","pos":"adj","meaning":"甜的","topic":"🍕 食物与饮食","subcategory":"食物形容词"},
    {"lesson":3,"word":"spicy","pos":"adj","meaning":"辣的","topic":"🍕 食物与饮食","subcategory":"食物形容词"},
    {"lesson":3,"word":"salty","pos":"adj","meaning":"咸的","topic":"🍕 食物与饮食","subcategory":"食物形容词"},
    {"lesson":3,"word":"savoury","pos":"adj","meaning":"咸香的","topic":"🍕 食物与饮食","subcategory":"食物形容词"},
    {"lesson":3,"word":"fresh","pos":"adj","meaning":"新鲜的","topic":"🍕 食物与饮食","subcategory":"食物形容词"},
    {"lesson":3,"word":"fatty","pos":"adj","meaning":"油腻的","topic":"🍕 食物与饮食","subcategory":"食物形容词"},
    {"lesson":3,"word":"disgusting","pos":"adj","meaning":"恶心的","topic":"🍕 食物与饮食","subcategory":"食物形容词"},
    {"lesson":3,"word":"horrible","pos":"adj","meaning":"难吃的；可怕的","topic":"🍕 食物与饮食","subcategory":"食物形容词"},
    {"lesson":3,"word":"well done","pos":"","meaning":"全熟（牛排）","topic":"🍕 食物与饮食","subcategory":"点餐用语"},
    {"lesson":3,"word":"order","pos":"v","meaning":"点餐","topic":"🍕 食物与饮食","subcategory":"点餐用语"},
    {"lesson":3,"word":"bill","pos":"n","meaning":"账单","topic":"🍕 食物与饮食","subcategory":"点餐用语"},
    {"lesson":3,"word":"menu","pos":"n","meaning":"菜单","topic":"🍕 食物与饮食","subcategory":"点餐用语"},
    {"lesson":3,"word":"breakfast","pos":"n","meaning":"早餐","topic":"🍕 食物与饮食","subcategory":"餐饮时间"},
    {"lesson":3,"word":"lunch","pos":"n","meaning":"午餐","topic":"🍕 食物与饮食","subcategory":"餐饮时间"},
    {"lesson":3,"word":"dinner","pos":"n","meaning":"晚餐","topic":"🍕 食物与饮食","subcategory":"餐饮时间"},
    {"lesson":3,"word":"headache","pos":"n","meaning":"头疼","topic":"🍕 食物与饮食","subcategory":"饮食健康"},

    // ============ Unit 4 - Family Ties ============
    {"lesson":4,"word":"family","pos":"n","meaning":"家庭","topic":"🧑 人物关系","subcategory":"家庭成员"},
    {"lesson":4,"word":"father","pos":"n","meaning":"父亲","topic":"🧑 人物关系","subcategory":"家庭成员"},
    {"lesson":4,"word":"mother","pos":"n","meaning":"母亲","topic":"🧑 人物关系","subcategory":"家庭成员"},
    {"lesson":4,"word":"parents","pos":"n","meaning":"父母","topic":"🧑 人物关系","subcategory":"家庭成员"},
    {"lesson":4,"word":"brother","pos":"n","meaning":"兄弟","topic":"🧑 人物关系","subcategory":"家庭成员"},
    {"lesson":4,"word":"sister","pos":"n","meaning":"姐妹","topic":"🧑 人物关系","subcategory":"家庭成员"},
    {"lesson":4,"word":"little brother","pos":"","meaning":"弟弟","topic":"🧑 人物关系","subcategory":"家庭成员"},
    {"lesson":4,"word":"big sister","pos":"","meaning":"姐姐","topic":"🧑 人物关系","subcategory":"家庭成员"},
    {"lesson":4,"word":"son","pos":"n","meaning":"儿子","topic":"🧑 人物关系","subcategory":"家庭成员"},
    {"lesson":4,"word":"daughter","pos":"n","meaning":"女儿","topic":"🧑 人物关系","subcategory":"家庭成员"},
    {"lesson":4,"word":"husband","pos":"n","meaning":"丈夫","topic":"🧑 人物关系","subcategory":"家庭成员"},
    {"lesson":4,"word":"wife","pos":"n","meaning":"妻子","topic":"🧑 人物关系","subcategory":"家庭成员"},
    {"lesson":4,"word":"grandparents","pos":"n","meaning":"祖父母","topic":"🧑 人物关系","subcategory":"家庭成员"},
    {"lesson":4,"word":"grandma","pos":"n","meaning":"奶奶/外婆","topic":"🧑 人物关系","subcategory":"家庭成员"},
    {"lesson":4,"word":"grandpa","pos":"n","meaning":"爷爷/外公","topic":"🧑 人物关系","subcategory":"家庭成员"},
    {"lesson":4,"word":"grandson","pos":"n","meaning":"孙子","topic":"🧑 人物关系","subcategory":"家庭成员"},
    {"lesson":4,"word":"granddaughter","pos":"n","meaning":"孙女","topic":"🧑 人物关系","subcategory":"家庭成员"},
    {"lesson":4,"word":"uncle","pos":"n","meaning":"叔叔/舅舅","topic":"🧑 人物关系","subcategory":"家庭成员"},
    {"lesson":4,"word":"aunt","pos":"n","meaning":"阿姨/姑姑","topic":"🧑 人物关系","subcategory":"家庭成员"},
    {"lesson":4,"word":"cousin","pos":"n","meaning":"表/堂兄弟姐妹","topic":"🧑 人物关系","subcategory":"家庭成员"},
    {"lesson":4,"word":"sister-in-law","pos":"n","meaning":"嫂子/弟媳","topic":"🧑 人物关系","subcategory":"家庭成员"},
    {"lesson":4,"word":"relatives","pos":"n","meaning":"亲戚","topic":"🧑 人物关系","subcategory":"家庭成员"},
    {"lesson":4,"word":"friend","pos":"n","meaning":"朋友","topic":"🧑 人物关系","subcategory":"人际关系"},
    {"lesson":4,"word":"celebrate","pos":"v","meaning":"庆祝","topic":"🧑 人物关系","subcategory":"家庭活动"},
    {"lesson":4,"word":"birthday","pos":"n","meaning":"生日","topic":"🧑 人物关系","subcategory":"家庭活动"},
    {"lesson":4,"word":"proud","pos":"adj","meaning":"自豪的","topic":"😊 情感与性格","subcategory":"情绪感受"},
    {"lesson":4,"word":"worried","pos":"adj","meaning":"担心的","topic":"😊 情感与性格","subcategory":"情绪感受"},
    {"lesson":4,"word":"upset","pos":"adj","meaning":"难过的","topic":"😊 情感与性格","subcategory":"情绪感受"},
    {"lesson":4,"word":"confused","pos":"adj","meaning":"困惑的","topic":"😊 情感与性格","subcategory":"情绪感受"},
    {"lesson":4,"word":"surprised","pos":"adj","meaning":"惊讶的","topic":"😊 情感与性格","subcategory":"情绪感受"},
    {"lesson":4,"word":"excited","pos":"adj","meaning":"兴奋的","topic":"😊 情感与性格","subcategory":"情绪感受"},
    {"lesson":4,"word":"angry","pos":"adj","meaning":"生气的","topic":"😊 情感与性格","subcategory":"情绪感受"},
    {"lesson":4,"word":"scared","pos":"adj","meaning":"害怕的","topic":"😊 情感与性格","subcategory":"情绪感受"},
    {"lesson":4,"word":"relieved","pos":"adj","meaning":"释然的","topic":"😊 情感与性格","subcategory":"情绪感受"},
    {"lesson":4,"word":"nervous","pos":"adj","meaning":"紧张的","topic":"😊 情感与性格","subcategory":"情绪感受"},
    {"lesson":4,"word":"happy","pos":"adj","meaning":"开心的","topic":"😊 情感与性格","subcategory":"情绪感受"},
    {"lesson":4,"word":"look like","pos":"","meaning":"看起来像","topic":"🏃 动作行为","subcategory":"常用动词"},

    // ============ Unit 5 - It's My Life ============
    {"lesson":5,"word":"living room","pos":"","meaning":"客厅","topic":"🏠 家居与设施","subcategory":"房间"},
    {"lesson":5,"word":"bedroom","pos":"n","meaning":"卧室","topic":"🏠 家居与设施","subcategory":"房间"},
    {"lesson":5,"word":"kitchen","pos":"n","meaning":"厨房","topic":"🏠 家居与设施","subcategory":"房间"},
    {"lesson":5,"word":"bathroom","pos":"n","meaning":"浴室","topic":"🏠 家居与设施","subcategory":"房间"},
    {"lesson":5,"word":"garden","pos":"n","meaning":"花园","topic":"🏠 家居与设施","subcategory":"房间"},
    {"lesson":5,"word":"garage","pos":"n","meaning":"车库","topic":"🏠 家居与设施","subcategory":"房间"},
    {"lesson":5,"word":"armchair","pos":"n","meaning":"扶手椅","topic":"🏠 家居与设施","subcategory":"家具"},
    {"lesson":5,"word":"sofa","pos":"n","meaning":"沙发","topic":"🏠 家居与设施","subcategory":"家具"},
    {"lesson":5,"word":"carpet","pos":"n","meaning":"地毯","topic":"🏠 家居与设施","subcategory":"家具"},
    {"lesson":5,"word":"curtains","pos":"n","meaning":"窗帘","topic":"🏠 家居与设施","subcategory":"家具"},
    {"lesson":5,"word":"lamp","pos":"n","meaning":"台灯","topic":"🏠 家居与设施","subcategory":"家具"},
    {"lesson":5,"word":"mirror","pos":"n","meaning":"镜子","topic":"🏠 家居与设施","subcategory":"家具"},
    {"lesson":5,"word":"shelves","pos":"n","meaning":"架子","topic":"🏠 家居与设施","subcategory":"家具"},
    {"lesson":5,"word":"wardrobe","pos":"n","meaning":"衣柜","topic":"🏠 家居与设施","subcategory":"家具"},
    {"lesson":5,"word":"desk","pos":"n","meaning":"书桌","topic":"🏠 家居与设施","subcategory":"家具"},
    {"lesson":5,"word":"bed","pos":"n","meaning":"床","topic":"🏠 家居与设施","subcategory":"家具"},
    {"lesson":5,"word":"cooker","pos":"n","meaning":"炉灶","topic":"🏠 家居与设施","subcategory":"家具"},
    {"lesson":5,"word":"fridge","pos":"n","meaning":"冰箱","topic":"🏠 家居与设施","subcategory":"家具"},
    {"lesson":5,"word":"shower","pos":"n","meaning":"淋浴","topic":"🏠 家居与设施","subcategory":"家具"},
    {"lesson":5,"word":"toilet","pos":"n","meaning":"马桶/厕所","topic":"🏠 家居与设施","subcategory":"家具"},
    {"lesson":5,"word":"key","pos":"n","meaning":"钥匙","topic":"🏠 家居与设施","subcategory":"日常物品"},
    {"lesson":5,"word":"bag","pos":"n","meaning":"包","topic":"🏠 家居与设施","subcategory":"日常物品"},
    {"lesson":5,"word":"look after","pos":"","meaning":"照顾","topic":"🏃 动作行为","subcategory":"look 短语"},
    {"lesson":5,"word":"look for","pos":"","meaning":"寻找","topic":"🏃 动作行为","subcategory":"look 短语"},
    {"lesson":5,"word":"look at","pos":"","meaning":"看","topic":"🏃 动作行为","subcategory":"look 短语"},
    {"lesson":5,"word":"look up","pos":"","meaning":"查阅","topic":"🏃 动作行为","subcategory":"look 短语"},
    {"lesson":5,"word":"look into","pos":"","meaning":"调查","topic":"🏃 动作行为","subcategory":"look 短语"},
    {"lesson":5,"word":"annoyed","pos":"adj","meaning":"恼怒的","topic":"😊 情感与性格","subcategory":"情绪感受"},
    {"lesson":5,"word":"relaxed","pos":"adj","meaning":"放松的","topic":"😊 情感与性格","subcategory":"情绪感受"},
    {"lesson":5,"word":"bored","pos":"adj","meaning":"无聊的","topic":"😊 情感与性格","subcategory":"情绪感受"},
    {"lesson":5,"word":"interested","pos":"adj","meaning":"感兴趣的","topic":"😊 情感与性格","subcategory":"情绪感受"},
    {"lesson":5,"word":"amazed","pos":"adj","meaning":"惊讶的","topic":"😊 情感与性格","subcategory":"情绪感受"},

    // ============ Unit 6 - Best Friends / Keeping Healthy ============
    {"lesson":6,"word":"yesterday","pos":"n","meaning":"昨天","topic":"📅 时间与顺序","subcategory":"过去时间"},
    {"lesson":6,"word":"ago","pos":"adv","meaning":"……以前","topic":"📅 时间与顺序","subcategory":"过去时间"},
    {"lesson":6,"word":"last night","pos":"","meaning":"昨晚","topic":"📅 时间与顺序","subcategory":"过去时间"},
    {"lesson":6,"word":"last week","pos":"","meaning":"上周","topic":"📅 时间与顺序","subcategory":"过去时间"},
    {"lesson":6,"word":"last month","pos":"","meaning":"上个月","topic":"📅 时间与顺序","subcategory":"过去时间"},
    {"lesson":6,"word":"last year","pos":"","meaning":"去年","topic":"📅 时间与顺序","subcategory":"过去时间"},
    {"lesson":6,"word":"intelligent","pos":"adj","meaning":"聪明的","topic":"😊 情感与性格","subcategory":"性格描述"},
    {"lesson":6,"word":"cheerful","pos":"adj","meaning":"快乐的","topic":"😊 情感与性格","subcategory":"性格描述"},
    {"lesson":6,"word":"jealous","pos":"adj","meaning":"嫉妒的","topic":"😊 情感与性格","subcategory":"性格描述"},
    {"lesson":6,"word":"helpful","pos":"adj","meaning":"乐于助人的","topic":"😊 情感与性格","subcategory":"性格描述"},
    {"lesson":6,"word":"confident","pos":"adj","meaning":"自信的","topic":"😊 情感与性格","subcategory":"性格描述"},
    {"lesson":6,"word":"generous","pos":"adj","meaning":"慷慨的","topic":"😊 情感与性格","subcategory":"性格描述"},
    {"lesson":6,"word":"easy-going","pos":"adj","meaning":"随和的","topic":"😊 情感与性格","subcategory":"性格描述"},
    {"lesson":6,"word":"funny","pos":"adj","meaning":"有趣的","topic":"😊 情感与性格","subcategory":"性格描述"},
    {"lesson":6,"word":"kind","pos":"adj","meaning":"善良的","topic":"😊 情感与性格","subcategory":"性格描述"},
    {"lesson":6,"word":"friendly","pos":"adj","meaning":"友好的","topic":"😊 情感与性格","subcategory":"性格描述"},
    {"lesson":6,"word":"shy","pos":"adj","meaning":"害羞的","topic":"😊 情感与性格","subcategory":"性格描述"},
    {"lesson":6,"word":"serious","pos":"adj","meaning":"严肃的","topic":"😊 情感与性格","subcategory":"性格描述"},
    {"lesson":6,"word":"healthy","pos":"adj","meaning":"健康的","topic":"⚽ 体育运动","subcategory":"健康"},
    {"lesson":6,"word":"exercise","pos":"n","meaning":"运动；锻炼","topic":"⚽ 体育运动","subcategory":"健康"},
    {"lesson":6,"word":"junk food","pos":"","meaning":"垃圾食品","topic":"🍕 食物与饮食","subcategory":"饮食健康"},
    {"lesson":6,"word":"vegetable","pos":"n","meaning":"蔬菜","topic":"🍕 食物与饮食","subcategory":"食材"},
    {"lesson":6,"word":"fruit","pos":"n","meaning":"水果","topic":"🍕 食物与饮食","subcategory":"食材"},
    {"lesson":6,"word":"should","pos":"v","meaning":"应该","topic":"🏃 动作行为","subcategory":"情态动词"},
    {"lesson":6,"word":"shouldn't","pos":"v","meaning":"不应该","topic":"🏃 动作行为","subcategory":"情态动词"},
    {"lesson":6,"word":"exam","pos":"n","meaning":"考试","topic":"🏫 教室与学习","subcategory":"学习用语"},
    {"lesson":6,"word":"mark","pos":"n","meaning":"分数","topic":"🏫 教室与学习","subcategory":"学习用语"},
    {"lesson":6,"word":"film","pos":"n","meaning":"电影","topic":"🎮 爱好与活动","subcategory":"娱乐"},
    {"lesson":6,"word":"party","pos":"n","meaning":"聚会","topic":"🎮 爱好与活动","subcategory":"社交活动"},

    // ============ Unit 7 - The Secrets of Success ============
    {"lesson":7,"word":"satnav","pos":"n","meaning":"卫星导航仪","topic":"💻 科技与设备","subcategory":"电子产品"},
    {"lesson":7,"word":"MP3 player","pos":"","meaning":"MP3播放器","topic":"💻 科技与设备","subcategory":"电子产品"},
    {"lesson":7,"word":"torch","pos":"n","meaning":"手电筒","topic":"💻 科技与设备","subcategory":"电子产品"},
    {"lesson":7,"word":"games console","pos":"","meaning":"游戏机","topic":"💻 科技与设备","subcategory":"电子产品"},
    {"lesson":7,"word":"remote control","pos":"","meaning":"遥控器","topic":"💻 科技与设备","subcategory":"电子产品"},
    {"lesson":7,"word":"coffee machine","pos":"","meaning":"咖啡机","topic":"💻 科技与设备","subcategory":"电子产品"},
    {"lesson":7,"word":"hair dryer","pos":"","meaning":"吹风机","topic":"💻 科技与设备","subcategory":"电子产品"},
    {"lesson":7,"word":"headphones","pos":"n","meaning":"耳机","topic":"💻 科技与设备","subcategory":"电子产品"},
    {"lesson":7,"word":"docking station","pos":"","meaning":"底座/拓展坞","topic":"💻 科技与设备","subcategory":"电子产品"},
    {"lesson":7,"word":"mobile phone","pos":"","meaning":"手机","topic":"💻 科技与设备","subcategory":"电子产品"},
    {"lesson":7,"word":"laptop","pos":"n","meaning":"笔记本电脑","topic":"💻 科技与设备","subcategory":"电子产品"},
    {"lesson":7,"word":"vacuum the floor","pos":"","meaning":"用吸尘器吸地板","topic":"🧹 家务","subcategory":"家务活"},
    {"lesson":7,"word":"tidy up","pos":"","meaning":"整理","topic":"🧹 家务","subcategory":"家务活"},
    {"lesson":7,"word":"do the ironing","pos":"","meaning":"熨衣服","topic":"🧹 家务","subcategory":"家务活"},
    {"lesson":7,"word":"do the shopping","pos":"","meaning":"购物","topic":"🧹 家务","subcategory":"家务活"},
    {"lesson":7,"word":"set the table","pos":"","meaning":"摆桌子","topic":"🧹 家务","subcategory":"家务活"},
    {"lesson":7,"word":"clear the table","pos":"","meaning":"收桌子","topic":"🧹 家务","subcategory":"家务活"},
    {"lesson":7,"word":"do the washing-up","pos":"","meaning":"洗碗","topic":"🧹 家务","subcategory":"家务活"},
    {"lesson":7,"word":"make the beds","pos":"","meaning":"铺床","topic":"🧹 家务","subcategory":"家务活"},
    {"lesson":7,"word":"do the cooking","pos":"","meaning":"做饭","topic":"🧹 家务","subcategory":"家务活"},
    {"lesson":7,"word":"load the dishwasher","pos":"","meaning":"装洗碗机","topic":"🧹 家务","subcategory":"家务活"},
    {"lesson":7,"word":"empty the dishwasher","pos":"","meaning":"清空洗碗机","topic":"🧹 家务","subcategory":"家务活"},
    {"lesson":7,"word":"holiday","pos":"n","meaning":"假期","topic":"📅 时间与顺序","subcategory":"时间表达"},
    {"lesson":7,"word":"weekend","pos":"n","meaning":"周末","topic":"📅 时间与顺序","subcategory":"时间表达"},

    // ============ Unit 8 - Going Wild ============
    {"lesson":8,"word":"sailing","pos":"n","meaning":"帆船运动","topic":"⚽ 体育运动","subcategory":"运动项目"},
    {"lesson":8,"word":"diving","pos":"n","meaning":"跳水/潜水","topic":"⚽ 体育运动","subcategory":"运动项目"},
    {"lesson":8,"word":"golf","pos":"n","meaning":"高尔夫","topic":"⚽ 体育运动","subcategory":"运动项目"},
    {"lesson":8,"word":"gymnastics","pos":"n","meaning":"体操","topic":"⚽ 体育运动","subcategory":"运动项目"},
    {"lesson":8,"word":"rock climbing","pos":"","meaning":"攀岩","topic":"⚽ 体育运动","subcategory":"运动项目"},
    {"lesson":8,"word":"rugby","pos":"n","meaning":"橄榄球","topic":"⚽ 体育运动","subcategory":"运动项目"},
    {"lesson":8,"word":"snowboarding","pos":"n","meaning":"单板滑雪","topic":"⚽ 体育运动","subcategory":"运动项目"},
    {"lesson":8,"word":"skiing","pos":"n","meaning":"滑雪","topic":"⚽ 体育运动","subcategory":"运动项目"},
    {"lesson":8,"word":"volleyball","pos":"n","meaning":"排球","topic":"⚽ 体育运动","subcategory":"运动项目"},
    {"lesson":8,"word":"windsurfing","pos":"n","meaning":"风帆冲浪","topic":"⚽ 体育运动","subcategory":"运动项目"},
    {"lesson":8,"word":"tennis","pos":"n","meaning":"网球","topic":"⚽ 体育运动","subcategory":"运动项目"},
    {"lesson":8,"word":"basketball","pos":"n","meaning":"篮球","topic":"⚽ 体育运动","subcategory":"运动项目"},
    {"lesson":8,"word":"football","pos":"n","meaning":"足球","topic":"⚽ 体育运动","subcategory":"运动项目"},
    {"lesson":8,"word":"swimming","pos":"n","meaning":"游泳","topic":"⚽ 体育运动","subcategory":"运动项目"},
    {"lesson":8,"word":"competition","pos":"n","meaning":"竞赛","topic":"⚽ 体育运动","subcategory":"赛事"},
    {"lesson":8,"word":"race","pos":"n","meaning":"比赛","topic":"⚽ 体育运动","subcategory":"赛事"},
    {"lesson":8,"word":"marathon","pos":"n","meaning":"马拉松","topic":"⚽ 体育运动","subcategory":"赛事"},
    {"lesson":8,"word":"take part","pos":"","meaning":"参加","topic":"🏃 动作行为","subcategory":"常用动词"},
    {"lesson":8,"word":"take place","pos":"","meaning":"举行","topic":"🏃 动作行为","subcategory":"常用动词"},
    {"lesson":8,"word":"at first","pos":"","meaning":"起初","topic":"📅 时间与顺序","subcategory":"序词"},
    {"lesson":8,"word":"then","pos":"adv","meaning":"然后","topic":"📅 时间与顺序","subcategory":"序词"},
    {"lesson":8,"word":"after that","pos":"","meaning":"之后","topic":"📅 时间与顺序","subcategory":"序词"},
    {"lesson":8,"word":"finally","pos":"adv","meaning":"最后","topic":"📅 时间与顺序","subcategory":"序词"},
    {"lesson":8,"word":"could","pos":"v","meaning":"可以；能（过去式）","topic":"🏃 动作行为","subcategory":"情态动词"},

    // ============ Unit 9 - The Wonders of the World ============
    {"lesson":9,"word":"beach","pos":"n","meaning":"海滩","topic":"🌍 自然地理","subcategory":"地形地貌"},
    {"lesson":9,"word":"desert","pos":"n","meaning":"沙漠","topic":"🌍 自然地理","subcategory":"地形地貌"},
    {"lesson":9,"word":"forest","pos":"n","meaning":"森林","topic":"🌍 自然地理","subcategory":"地形地貌"},
    {"lesson":9,"word":"hill","pos":"n","meaning":"小山","topic":"🌍 自然地理","subcategory":"地形地貌"},
    {"lesson":9,"word":"island","pos":"n","meaning":"岛屿","topic":"🌍 自然地理","subcategory":"地形地貌"},
    {"lesson":9,"word":"jungle","pos":"n","meaning":"丛林","topic":"🌍 自然地理","subcategory":"地形地貌"},
    {"lesson":9,"word":"lake","pos":"n","meaning":"湖泊","topic":"🌍 自然地理","subcategory":"地形地貌"},
    {"lesson":9,"word":"mountain","pos":"n","meaning":"高山","topic":"🌍 自然地理","subcategory":"地形地貌"},
    {"lesson":9,"word":"ocean","pos":"n","meaning":"海洋","topic":"🌍 自然地理","subcategory":"地形地貌"},
    {"lesson":9,"word":"river","pos":"n","meaning":"河流","topic":"🌍 自然地理","subcategory":"地形地貌"},
    {"lesson":9,"word":"sea","pos":"n","meaning":"大海","topic":"🌍 自然地理","subcategory":"地形地貌"},
    {"lesson":9,"word":"cloudy","pos":"adj","meaning":"多云的","topic":"⛅ 天气","subcategory":"天气描述"},
    {"lesson":9,"word":"sunny","pos":"adj","meaning":"晴朗的","topic":"⛅ 天气","subcategory":"天气描述"},
    {"lesson":9,"word":"rainy","pos":"adj","meaning":"下雨的","topic":"⛅ 天气","subcategory":"天气描述"},
    {"lesson":9,"word":"windy","pos":"adj","meaning":"有风的","topic":"⛅ 天气","subcategory":"天气描述"},
    {"lesson":9,"word":"foggy","pos":"adj","meaning":"有雾的","topic":"⛅ 天气","subcategory":"天气描述"},
    {"lesson":9,"word":"freezing","pos":"adj","meaning":"极冷的","topic":"⛅ 天气","subcategory":"天气描述"},
    {"lesson":9,"word":"hot","pos":"adj","meaning":"炎热的","topic":"⛅ 天气","subcategory":"天气描述"},
    {"lesson":9,"word":"warm","pos":"adj","meaning":"温暖的","topic":"⛅ 天气","subcategory":"天气描述"},
    {"lesson":9,"word":"cold","pos":"adj","meaning":"冷的","topic":"⛅ 天气","subcategory":"天气描述"},
    {"lesson":9,"word":"dry","pos":"adj","meaning":"干燥的","topic":"⛅ 天气","subcategory":"天气描述"},
    {"lesson":9,"word":"wet","pos":"adj","meaning":"潮湿的","topic":"⛅ 天气","subcategory":"天气描述"},
    {"lesson":9,"word":"tall","pos":"adj","meaning":"高的","topic":"🌟 描述形容词","subcategory":"大小形状"},
    {"lesson":9,"word":"short","pos":"adj","meaning":"矮的；短的","topic":"🌟 描述形容词","subcategory":"大小形状"},
    {"lesson":9,"word":"big","pos":"adj","meaning":"大的","topic":"🌟 描述形容词","subcategory":"大小形状"},
    {"lesson":9,"word":"small","pos":"adj","meaning":"小的","topic":"🌟 描述形容词","subcategory":"大小形状"},
    {"lesson":9,"word":"fast","pos":"adj","meaning":"快的","topic":"🌟 描述形容词","subcategory":"事物特征"},
    {"lesson":9,"word":"slow","pos":"adj","meaning":"慢的","topic":"🌟 描述形容词","subcategory":"事物特征"},
    {"lesson":9,"word":"easy","pos":"adj","meaning":"简单的","topic":"🌟 描述形容词","subcategory":"事物特征"},
    {"lesson":9,"word":"difficult","pos":"adj","meaning":"困难的","topic":"🌟 描述形容词","subcategory":"事物特征"},
    {"lesson":9,"word":"beautiful","pos":"adj","meaning":"美丽的","topic":"🌟 描述形容词","subcategory":"事物特征"},
    {"lesson":9,"word":"dangerous","pos":"adj","meaning":"危险的","topic":"🌟 描述形容词","subcategory":"事物特征"},
    {"lesson":9,"word":"safe","pos":"adj","meaning":"安全的","topic":"🌟 描述形容词","subcategory":"事物特征"},
    {"lesson":9,"word":"good","pos":"adj","meaning":"好的","topic":"🌟 描述形容词","subcategory":"基础形容词"},
    {"lesson":9,"word":"bad","pos":"adj","meaning":"坏的","topic":"🌟 描述形容词","subcategory":"基础形容词"},
    {"lesson":9,"word":"better","pos":"adj","meaning":"更好的","topic":"🌟 描述形容词","subcategory":"比较级"},
    {"lesson":9,"word":"best","pos":"adj","meaning":"最好的","topic":"🌟 描述形容词","subcategory":"最高级"},
    {"lesson":9,"word":"worse","pos":"adj","meaning":"更坏的","topic":"🌟 描述形容词","subcategory":"比较级"},
    {"lesson":9,"word":"worst","pos":"adj","meaning":"最坏的","topic":"🌟 描述形容词","subcategory":"最高级"},
    {"lesson":9,"word":"far","pos":"adj","meaning":"远的","topic":"🌟 描述形容词","subcategory":"大小形状"},

    // ============ Unit 10 - People and Places ============
    {"lesson":10,"word":"concert hall","pos":"","meaning":"音乐厅","topic":"🏙️ 城镇与交通","subcategory":"城镇场所"},
    {"lesson":10,"word":"car park","pos":"","meaning":"停车场","topic":"🏙️ 城镇与交通","subcategory":"城镇场所"},
    {"lesson":10,"word":"shopping mall","pos":"","meaning":"购物中心","topic":"🏙️ 城镇与交通","subcategory":"城镇场所"},
    {"lesson":10,"word":"bus station","pos":"","meaning":"公交总站","topic":"🏙️ 城镇与交通","subcategory":"城镇场所"},
    {"lesson":10,"word":"police station","pos":"","meaning":"警察局","topic":"🏙️ 城镇与交通","subcategory":"城镇场所"},
    {"lesson":10,"word":"post office","pos":"","meaning":"邮局","topic":"🏙️ 城镇与交通","subcategory":"城镇场所"},
    {"lesson":10,"word":"football stadium","pos":"","meaning":"足球场","topic":"🏙️ 城镇与交通","subcategory":"城镇场所"},
    {"lesson":10,"word":"sports centre","pos":"","meaning":"体育中心","topic":"🏙️ 城镇与交通","subcategory":"城镇场所"},
    {"lesson":10,"word":"zebra crossing","pos":"","meaning":"斑马线","topic":"🏙️ 城镇与交通","subcategory":"城镇场所"},
    {"lesson":10,"word":"youth club","pos":"","meaning":"青少年俱乐部","topic":"🏙️ 城镇与交通","subcategory":"城镇场所"},
    {"lesson":10,"word":"park","pos":"n","meaning":"公园","topic":"🏙️ 城镇与交通","subcategory":"城镇场所"},
    {"lesson":10,"word":"library","pos":"n","meaning":"图书馆","topic":"🏙️ 城镇与交通","subcategory":"城镇场所"},
    {"lesson":10,"word":"hospital","pos":"n","meaning":"医院","topic":"🏙️ 城镇与交通","subcategory":"城镇场所"},
    {"lesson":10,"word":"restaurant","pos":"n","meaning":"餐厅","topic":"🏙️ 城镇与交通","subcategory":"城镇场所"},
    {"lesson":10,"word":"cinema","pos":"n","meaning":"电影院","topic":"🏙️ 城镇与交通","subcategory":"城镇场所"},
    {"lesson":10,"word":"museum","pos":"n","meaning":"博物馆","topic":"🏙️ 城镇与交通","subcategory":"城镇场所"},
    {"lesson":10,"word":"hotel","pos":"n","meaning":"酒店","topic":"🏙️ 城镇与交通","subcategory":"城镇场所"},
    {"lesson":10,"word":"bank","pos":"n","meaning":"银行","topic":"🏙️ 城镇与交通","subcategory":"城镇场所"},
    {"lesson":10,"word":"church","pos":"n","meaning":"教堂","topic":"🏙️ 城镇与交通","subcategory":"城镇场所"},
    {"lesson":10,"word":"speed camera","pos":"","meaning":"测速摄像头","topic":"🏙️ 城镇与交通","subcategory":"交通设施"},
    {"lesson":10,"word":"graffiti wall","pos":"","meaning":"涂鸦墙","topic":"🏙️ 城镇与交通","subcategory":"交通设施"},
    {"lesson":10,"word":"cycle lane","pos":"","meaning":"自行车道","topic":"🏙️ 城镇与交通","subcategory":"交通设施"},
    {"lesson":10,"word":"litter bin","pos":"","meaning":"垃圾桶","topic":"🏙️ 城镇与交通","subcategory":"交通设施"},
    {"lesson":10,"word":"billboard","pos":"n","meaning":"广告牌","topic":"🏙️ 城镇与交通","subcategory":"交通设施"},
    {"lesson":10,"word":"high street","pos":"","meaning":"商业街","topic":"🏙️ 城镇与交通","subcategory":"交通设施"},
    {"lesson":10,"word":"bridge","pos":"n","meaning":"桥","topic":"🏙️ 城镇与交通","subcategory":"交通设施"},
    {"lesson":10,"word":"street","pos":"n","meaning":"街道","topic":"🏙️ 城镇与交通","subcategory":"交通设施"},
    {"lesson":10,"word":"road","pos":"n","meaning":"路","topic":"🏙️ 城镇与交通","subcategory":"交通设施"},
    {"lesson":10,"word":"traffic light","pos":"","meaning":"红绿灯","topic":"🏙️ 城镇与交通","subcategory":"交通设施"},
    {"lesson":10,"word":"corner","pos":"n","meaning":"拐角","topic":"🏙️ 城镇与交通","subcategory":"问路指路"},
    {"lesson":10,"word":"go straight on","pos":"","meaning":"直走","topic":"🏙️ 城镇与交通","subcategory":"问路指路"},
    {"lesson":10,"word":"turn left","pos":"","meaning":"左转","topic":"🏙️ 城镇与交通","subcategory":"问路指路"},
    {"lesson":10,"word":"turn right","pos":"","meaning":"右转","topic":"🏙️ 城镇与交通","subcategory":"问路指路"},
    {"lesson":10,"word":"tomorrow","pos":"n","meaning":"明天","topic":"📅 时间与顺序","subcategory":"将来时间"},
    {"lesson":10,"word":"soon","pos":"adv","meaning":"不久","topic":"📅 时间与顺序","subcategory":"将来时间"},
    {"lesson":10,"word":"next week","pos":"","meaning":"下周","topic":"📅 时间与顺序","subcategory":"将来时间"},
    {"lesson":10,"word":"next month","pos":"","meaning":"下个月","topic":"📅 时间与顺序","subcategory":"将来时间"},
    {"lesson":10,"word":"next year","pos":"","meaning":"明年","topic":"📅 时间与顺序","subcategory":"将来时间"},
    {"lesson":10,"word":"in the future","pos":"","meaning":"在将来","topic":"📅 时间与顺序","subcategory":"将来时间"},
    {"lesson":10,"word":"will","pos":"v","meaning":"将；会","topic":"🏃 动作行为","subcategory":"情态动词"},

    // ============ Unit 11 - Making a Difference ============
    {"lesson":11,"word":"volunteer","pos":"n","meaning":"志愿者","topic":"🏃 动作行为","subcategory":"慈善志愿"},
    {"lesson":11,"word":"charity","pos":"n","meaning":"慈善","topic":"🏃 动作行为","subcategory":"慈善志愿"},
    {"lesson":11,"word":"ever","pos":"adv","meaning":"曾经","topic":"📅 时间与顺序","subcategory":"现在完成时"},
    {"lesson":11,"word":"for","pos":"prep","meaning":"持续（时间段）","topic":"📅 时间与顺序","subcategory":"现在完成时"},
    {"lesson":11,"word":"since","pos":"prep","meaning":"自从","topic":"📅 时间与顺序","subcategory":"现在完成时"},
    {"lesson":11,"word":"before","pos":"adv","meaning":"以前","topic":"📅 时间与顺序","subcategory":"现在完成时"},

    // ============ Unit 12 - The Way We Are ============
    {"lesson":12,"word":"lifestyle","pos":"n","meaning":"生活方式","topic":"🌟 描述形容词","subcategory":"生活方式"},
    {"lesson":12,"word":"opinion","pos":"n","meaning":"观点","topic":"💬 观点表达","subcategory":"表达观点"},
    {"lesson":12,"word":"agree","pos":"v","meaning":"同意","topic":"💬 观点表达","subcategory":"表达观点"},
    {"lesson":12,"word":"disagree","pos":"v","meaning":"不同意","topic":"💬 观点表达","subcategory":"表达观点"},
    {"lesson":12,"word":"different","pos":"adj","meaning":"不同的","topic":"🌟 描述形容词","subcategory":"事物特征"},
    {"lesson":12,"word":"important","pos":"adj","meaning":"重要的","topic":"🌟 描述形容词","subcategory":"事物特征"},

    // ============ 跨单元不规则动词 (U6-U7重点) ============
    {"lesson":7,"word":"go","pos":"v","meaning":"去","topic":"🏃 动作行为","subcategory":"不规则动词"},
    {"lesson":7,"word":"do","pos":"v","meaning":"做","topic":"🏃 动作行为","subcategory":"不规则动词"},
    {"lesson":7,"word":"have","pos":"v","meaning":"有","topic":"🏃 动作行为","subcategory":"不规则动词"},
    {"lesson":7,"word":"come","pos":"v","meaning":"来","topic":"🏃 动作行为","subcategory":"不规则动词"},
    {"lesson":7,"word":"get","pos":"v","meaning":"得到","topic":"🏃 动作行为","subcategory":"不规则动词"},
    {"lesson":7,"word":"see","pos":"v","meaning":"看见","topic":"🏃 动作行为","subcategory":"不规则动词"},
    {"lesson":7,"word":"make","pos":"v","meaning":"制作","topic":"🏃 动作行为","subcategory":"不规则动词"},
    {"lesson":7,"word":"eat","pos":"v","meaning":"吃","topic":"🏃 动作行为","subcategory":"不规则动词"},
    {"lesson":7,"word":"drink","pos":"v","meaning":"喝","topic":"🏃 动作行为","subcategory":"不规则动词"},
    {"lesson":7,"word":"give","pos":"v","meaning":"给","topic":"🏃 动作行为","subcategory":"不规则动词"},
    {"lesson":7,"word":"take","pos":"v","meaning":"拿","topic":"🏃 动作行为","subcategory":"不规则动词"},
    {"lesson":7,"word":"write","pos":"v","meaning":"写","topic":"🏃 动作行为","subcategory":"不规则动词"},
    {"lesson":7,"word":"read","pos":"v","meaning":"阅读","topic":"🏃 动作行为","subcategory":"不规则动词"},
    {"lesson":7,"word":"think","pos":"v","meaning":"想","topic":"🏃 动作行为","subcategory":"不规则动词"},
    {"lesson":7,"word":"know","pos":"v","meaning":"知道","topic":"🏃 动作行为","subcategory":"不规则动词"},
    {"lesson":7,"word":"find","pos":"v","meaning":"找到","topic":"🏃 动作行为","subcategory":"不规则动词"},
    {"lesson":7,"word":"tell","pos":"v","meaning":"告诉","topic":"🏃 动作行为","subcategory":"不规则动词"},
    {"lesson":7,"word":"say","pos":"v","meaning":"说","topic":"🏃 动作行为","subcategory":"不规则动词"},
    {"lesson":7,"word":"speak","pos":"v","meaning":"讲","topic":"🏃 动作行为","subcategory":"不规则动词"},

    // ============ 规则动词（常用）============
    {"lesson":6,"word":"play","pos":"v","meaning":"玩","topic":"🏃 动作行为","subcategory":"常用动词"},
    {"lesson":6,"word":"walk","pos":"v","meaning":"步行","topic":"🏃 动作行为","subcategory":"常用动词"},
    {"lesson":6,"word":"like","pos":"v","meaning":"喜欢","topic":"🏃 动作行为","subcategory":"常用动词"},
    {"lesson":6,"word":"live","pos":"v","meaning":"居住","topic":"🏃 动作行为","subcategory":"常用动词"},
    {"lesson":6,"word":"study","pos":"v","meaning":"学习","topic":"🏃 动作行为","subcategory":"常用动词"},
    {"lesson":6,"word":"carry","pos":"v","meaning":"携带","topic":"🏃 动作行为","subcategory":"常用动词"},
    {"lesson":6,"word":"stop","pos":"v","meaning":"停止","topic":"🏃 动作行为","subcategory":"常用动词"},
    {"lesson":6,"word":"plan","pos":"v","meaning":"计划","topic":"🏃 动作行为","subcategory":"常用动词"},
    {"lesson":6,"word":"want","pos":"v","meaning":"想要","topic":"🏃 动作行为","subcategory":"常用动词"},
    {"lesson":6,"word":"help","pos":"v","meaning":"帮助","topic":"🏃 动作行为","subcategory":"常用动词"},
    {"lesson":6,"word":"watch","pos":"v","meaning":"观看","topic":"🏃 动作行为","subcategory":"常用动词"},
    {"lesson":6,"word":"start","pos":"v","meaning":"开始","topic":"🏃 动作行为","subcategory":"常用动词"},
    {"lesson":6,"word":"finish","pos":"v","meaning":"完成","topic":"🏃 动作行为","subcategory":"常用动词"},
    {"lesson":6,"word":"visit","pos":"v","meaning":"参观","topic":"🏃 动作行为","subcategory":"常用动词"},
    {"lesson":6,"word":"travel","pos":"v","meaning":"旅行","topic":"🏃 动作行为","subcategory":"常用动词"},
    {"lesson":6,"word":"stay","pos":"v","meaning":"停留","topic":"🏃 动作行为","subcategory":"常用动词"},
    {"lesson":6,"word":"love","pos":"v","meaning":"热爱","topic":"🏃 动作行为","subcategory":"常用动词"},
    {"lesson":6,"word":"hate","pos":"v","meaning":"讨厌","topic":"🏃 动作行为","subcategory":"常用动词"},
    {"lesson":6,"word":"join","pos":"v","meaning":"加入","topic":"🏃 动作行为","subcategory":"常用动词"},
    {"lesson":6,"word":"try","pos":"v","meaning":"尝试","topic":"🏃 动作行为","subcategory":"常用动词"},

    // ============ 数量表达 (U2-U3关键语法) ============
    {"lesson":2,"word":"some","pos":"adj","meaning":"一些","topic":"🌟 描述形容词","subcategory":"数量表达"},
    {"lesson":2,"word":"any","pos":"adj","meaning":"任何","topic":"🌟 描述形容词","subcategory":"数量表达"},
    {"lesson":2,"word":"many","pos":"adj","meaning":"许多（可数）","topic":"🌟 描述形容词","subcategory":"数量表达"},
    {"lesson":2,"word":"much","pos":"adj","meaning":"许多（不可数）","topic":"🌟 描述形容词","subcategory":"数量表达"},
    {"lesson":2,"word":"a lot of","pos":"","meaning":"许多","topic":"🌟 描述形容词","subcategory":"数量表达"},
    {"lesson":2,"word":"a few","pos":"","meaning":"几个","topic":"🌟 描述形容词","subcategory":"数量表达"},
    {"lesson":2,"word":"a little","pos":"","meaning":"一点","topic":"🌟 描述形容词","subcategory":"数量表达"}
  ]
};

if (typeof module !== 'undefined' && module.exports) {
  module.exports = vocabulary;
}
